import React,{useEffect,useRef,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const API="http://127.0.0.1:8000";
function App(){const[file,setFile]=useState(null),[preview,setPreview]=useState(""),[result,setResult]=useState(null),[history,setHistory]=useState([]),[loading,setLoading]=useState(false),[camera,setCamera]=useState(false);const video=useRef(null),stream=useRef(null);
async function load(){try{setHistory(await(await fetch(API+"/api/inspections")).json())}catch{}}
useEffect(()=>{load();return()=>stream.current?.getTracks().forEach(t=>t.stop())},[]);
function choose(f){if(!f)return;setFile(f);setPreview(URL.createObjectURL(f));setResult(null)}
async function inspect(){if(!file)return alert("Select or capture an image first.");let fd=new FormData();fd.append("image",file);setLoading(true);try{let r=await fetch(API+"/api/inspect",{method:"POST",body:fd});if(!r.ok)throw 0;setResult(await r.json());load()}catch{alert("Backend connection failed. Start FastAPI first.")}finally{setLoading(false)}}
async function startCamera(){try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});video.current.srcObject=stream.current;setCamera(true)}catch{alert("Camera permission unavailable.")}}
function capture(){let c=document.createElement("canvas");c.width=video.current.videoWidth;c.height=video.current.videoHeight;c.getContext("2d").drawImage(video.current,0,0);c.toBlob(b=>{choose(new File([b],"camera.jpg",{type:"image/jpeg"}));stream.current?.getTracks().forEach(t=>t.stop());setCamera(false)},"image/jpeg")}
return <div className="app"><header><div><h1>Quality<span>Inspect</span></h1><p>PS-07 • Automated Manufacturing Quality Control</p></div><b>● SYSTEM ONLINE</b></header><main><section className="hero"><h2>AI Quality Inspection</h2><p>Upload or capture a product image and receive a calibrated Pass / Fail / Human Review decision.</p></section><section className="grid"><div className="card"><h3>1. Product Input</h3><div className="drop">{preview?<img src={preview}/>:<div className="placeholder">📦<br/><b>No product image</b><small>Upload an image or use camera</small></div>}</div><div className="actions"><label className="btn">Upload<input hidden type="file" accept="image/*" onChange={e=>choose(e.target.files[0])}/></label><button className="btn secondary" onClick={startCamera}>📷 Camera</button></div>{camera&&<div className="camera"><video ref={video} autoPlay playsInline/><button className="btn" onClick={capture}>Capture</button></div>}<button className="inspect" onClick={inspect} disabled={loading}>{loading?"Analyzing...":"Run Quality Inspection →"}</button></div><div className="card"><h3>2. Inspection Result</h3>{!result?<div className="empty">Waiting for inspection</div>:<><div className={"decision "+result.decision.toLowerCase().replace(" ","-")}><strong>{result.decision}</strong><span>{Math.round(result.confidence*100)}% confidence</span></div><div className="metrics"><div><small>Defect score</small><b>{result.defect_score.toFixed(3)}</b></div><div><small>Threshold</small><b>{result.threshold.toFixed(3)}</b></div></div><p><b>Reason:</b> {result.reason}</p><p><b>Inspection ID:</b> {result.id}</p></>}</div></section><section className="card"><div className="sectionhead"><h3>Inspection History</h3><button onClick={load}>Refresh</button></div><div className="table"><div className="tr head"><span>ID</span><span>Decision</span><span>Confidence</span><span>Score</span><span>Time</span></div>{history.length?history.map(x=><div className="tr" key={x.id}><span>#{x.id}</span><span className={x.decision.toLowerCase().replace(" ","-")}>{x.decision}</span><span>{Math.round(x.confidence*100)}%</span><span>{Number(x.defect_score).toFixed(3)}</span><span>{new Date(x.created_at).toLocaleString()}</span></div>):<div className="empty">No inspections yet.</div>}</div></section></main></div>}
createRoot(document.getElementById("root")).render(<App/>);